// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCg33ySUwsD7YA2l7w6P9jrlEzuwMmBTIg',
//     appId: '1:488106502007:web:46ba68caecec1082582372',
//     messagingSenderId: '488106502007',
//     projectId: 'hey-tutor-e382a',
//     authDomain: 'hey-tutor-e382a.firebaseapp.com',
//     storageBucket: 'hey-tutor-e382a.firebasestorage.app',
//     measurementId: 'G-68FK8EYQR5',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD-SWy8ISvQV2E9kmnsb1U9HrcVwIeuow0',
//     appId: '1:488106502007:android:d75aace9bcfb40c6582372',
//     messagingSenderId: '488106502007',
//     projectId: 'hey-tutor-e382a',
//     storageBucket: 'hey-tutor-e382a.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC1wQ7dCTupf0sKn5GuTc8MUveiRWoyA5U',
//     appId: '1:488106502007:ios:656e3a08b04ef80b582372',
//     messagingSenderId: '488106502007',
//     projectId: 'hey-tutor-e382a',
//     storageBucket: 'hey-tutor-e382a.firebasestorage.app',
//     iosBundleId: 'com.example.heyTutor',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC1wQ7dCTupf0sKn5GuTc8MUveiRWoyA5U',
//     appId: '1:488106502007:ios:656e3a08b04ef80b582372',
//     messagingSenderId: '488106502007',
//     projectId: 'hey-tutor-e382a',
//     storageBucket: 'hey-tutor-e382a.firebasestorage.app',
//     iosBundleId: 'com.example.heyTutor',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCg33ySUwsD7YA2l7w6P9jrlEzuwMmBTIg',
//     appId: '1:488106502007:web:bf733cd518f61f79582372',
//     messagingSenderId: '488106502007',
//     projectId: 'hey-tutor-e382a',
//     authDomain: 'hey-tutor-e382a.firebaseapp.com',
//     storageBucket: 'hey-tutor-e382a.firebasestorage.app',
//
//     measurementId: 'G-G3X9FBBNZS',
//   );
// }

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg33ySUwsD7YA2l7w6P9jrlEzuwMmBTIg',
    appId: '1:488106502007:web:46ba68caecec1082582372',
    messagingSenderId: '488106502007',
    projectId: 'hey-tutor-e382a',
    authDomain: 'hey-tutor-e382a.firebaseapp.com',
    storageBucket: 'hey-tutor-e382a.firebasestorage.app',
    measurementId: 'G-68FK8EYQR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SWy8ISvQV2E9kmnsb1U9HrcVwIeuow0',
    appId: '1:488106502007:android:d75aace9bcfb40c6582372',
    messagingSenderId: '488106502007',
    projectId: 'hey-tutor-e382a',
    storageBucket: 'hey-tutor-e382a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1wQ7dCTupf0sKn5GuTc8MUveiRWoyA5U',
    appId: '1:488106502007:ios:656e3a08b04ef80b582372',
    messagingSenderId: '488106502007',
    projectId: 'hey-tutor-e382a',
    storageBucket: 'hey-tutor-e382a.firebasestorage.app',
    iosBundleId: 'com.example.heyTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1wQ7dCTupf0sKn5GuTc8MUveiRWoyA5U',
    appId: '1:488106502007:ios:656e3a08b04ef80b582372',
    messagingSenderId: '488106502007',
    projectId: 'hey-tutor-e382a',
    storageBucket: 'hey-tutor-e382a.firebasestorage.app',
    iosBundleId: 'com.example.heyTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg33ySUwsD7YA2l7w6P9jrlEzuwMmBTIg',
    appId: '1:488106502007:web:bf733cd518f61f79582372',
    messagingSenderId: '488106502007',
    projectId: 'hey-tutor-e382a',
    authDomain: 'hey-tutor-e382a.firebaseapp.com',
    storageBucket: 'hey-tutor-e382a.firebasestorage.app',
    measurementId: 'G-G3X9FBBNZS',
  );
}
